config:
  catalog: "ademianczuk"
  schema: "flights"
  owner:
    fName: "Andrij"
    lName: "Demianczuk"
    organization: "Databricks"
    email: "andrij.demianczuk@databricks.com"

flights:
  count: 4

developer:
  debug: True